### PR TITLE
Convert jQuery codes into vanilla js

### LINKED ISSUE #156: Convert jQuery to vanilla JavaScript in app.js
1. Change the jQuery code in app.js to vanilla JavaScript. 
2. Add additional comments explaining what the code is doing if needed. 
3. Remove the jQuery link in the index.html file.

### PR DESCRIPTION
**Pull request by Seniru**
Hello! This will close #156 which asks to change the whole code to vanilla js instead of using jQuery. 
Here are the changes to the code with this PR
- [x] Adding additional comments
- [x] Remove the jQuery script tag from the HTML
- [x] Converting jQuery codes to vanilla JS

### CODE REVIEW

**Comment by Seniru** [comment]
@brittanyrw the work is done!

**Comment by brittanyrw** [comment]
@Seniru Thanks for working on this, looks great! 

Once some other features are completed (they are in progress and probably using jQuery so I want to wait until they are done and then translate that over to vanilla JS) I will get this merged in.

**Comment by Seniru** [comment]
OK

**Comment by Seniru** [comment]
It looks like there are some conflicts. Can you tell what are the changes that are proposed to do @brittanyrw ?

**Pull request closed without merging**
