### PR TITLE
Added Fargo

### PR DESCRIPTION
**Pull request by prashi23**
- [x] 🔍 I have searched the `data.json` file and confirmed I am not adding a duplicate entry.
- [x] 🌈 I have added a single year under `date`. Note: Do not add ranges such as 2017-2019. 
- [x] 📅 I have added a type from one of the following: `movie` , `tv` or `musical`.
- [x] 3️⃣ I have at least three emojis listed under `emojiImgs`
- [x] 5️⃣ I have a maximum of five emojis listed under `emojiImgs`.
- [x] 👍 My pull request has a descriptive title (such as `Added The Lion King` or `Added Black Panther, The Avengers: Endgame and Thor`)
- [x] ⭐ My genres are all inside of square brackets `[ ]` and each are individually wrapped in quotation marks and have a comma between each one. (such as submitting this `"genres": ["adventure","mystery","animation"]` and not this `"genres":["adventure, mystery, animation"]`)
- [x] 🖍️ I have placed the new show(s) or movie(s) in alphabetical order based on title. 

👋 If this pull request closes an issue, replace the --- with the issue number.

Closes #---

### CODE REVIEW

**Review by brittanyrw — APPROVED** [review]

**Comment by brittanyrw** [comment]
@prashi23 Everything looks great! You should be able to see what you have added on emojiscreen.com. Thanks for contributing to EmojiScreen! 💖🥳

**Comment by prashi23** [comment]
> @prashi23 Everything looks great! You should be able to see what you have added on emojiscreen.com. Thanks for contributing to EmojiScreen! 🥳

Thanks for adding. Your project is really cool. I will work on more issues. 😍🤗

**Comment by brittanyrw** [comment]
@prashi23 Glad to hear that! I updated the structure of the app today so that it is no longer using data.json and is using data.js instead. So if you would like to make more pull requests, just make sure to update your fork with the new changes or delete your current fork and make a new one, if that is easier.

**Comment by prashi23** [comment]
> @prashi23 Glad to hear that! I updated the structure of the app today so that it is no longer using data.json and is using data.js instead. So if you would like to make more pull requests, just make sure to update your fork with the new changes or delete your current fork and make a new one, if that is easier.

Okay, gotcha!

**Pull request merged**
