### PR TITLE
Added Edward Sicssorhands

### LINKED ISSUE #348: Add Edward Scissorhands (Movie) to EmojiScreen
Link: https://www.imdb.com/title/tt0099487/

### PR DESCRIPTION
**Pull request by susanahan**
- [x ] 🔍 I have searched the `data.js` file and confirmed I am not adding a duplicate entry. Note: Different versions of the same show/movie are okay to add such as Lion King (1994) and Lion King (2019) or Rent (movie) and Rent (musical).
- [x ] 🌈 I have added a single year under `year`. Note: Do not add ranges such as 2017-2019.
- [x ] 📅 I have added a type from one of the following: `movie` , `tv` or `musical`.
- [ x] 🔗 I have added the IMDB page or Playbill archive page under `itemLink`.
- [x ] 3️⃣ I have at least three emojis listed under `emojiImgs`.
- [x ] 5️⃣ I have a maximum of five emojis listed under `emojiImgs`.
- [x ] 👍 My pull request has a descriptive title (such as `Added The Lion King` or `Added Black Panther, The Avengers: Endgame and Thor`).
- [x ] ⭐ My genres are all inside of square brackets `[ ]` and each are individually wrapped in quotation marks and have a comma between each one. (such as submitting this `"genres": ["adventure","mystery","animation"]` and not this `"genres":["adventure, mystery, animation"]`).
- [x ] 🖍️ I have placed the new show(s) or movie(s) in alphabetical order based on title. If the show or movie starts with 'the', then use the second word to alphabetize.

Closes #348

### CODE REVIEW

**Comment by susanahan** [comment]
@brittanyrw not fully sure how Hacktoberfest works but can you wait until 10/1 to approve it so it counts? 😭

**Comment by brittanyrw** [comment]
@susanahan For Hacktoberfest, it actually is counting **when** you make the pull request and not when the pull request is approved or merged. So you should wait to make the pull requests in October for them to count for Hacktoberfest.

Did you want to close this and then make a new pull request for this in October? I will make sure to not accept any pull requests from other people for the Issues that you have already been assigned. 🙂

**Review by brittanyrw — APPROVED** [review]

**Comment by brittanyrw** [comment]
@susanahan thanks for contributing to EmojiScreen! 💜You should be able to see your addition at [emojiscreen.com](emojiscreen.com) soon.

**Comment by susanahan** [comment]
@brittanyrw you rock! thank you and _sorry for the delay_ 😭

**Pull request merged**
