### PR TITLE
Added Boyhood (2014)

### PR DESCRIPTION
**Pull request by wdixon2186**
Follow the checklist below when working on adding a card. This will help you double check that you have everything you need to have your Pull Request approved.

 [x]🔎 Have searched the data.js file and Pull Requests to make sure that you are not adding a duplicate.
[x] 🖍️ Place the new show(s) or movie(s) in alphabetical order based on title. If the show or movie starts with 'the', then use the second word to alphabetize.
 [x]🌈 There is a single year under year.
 [x]📅 There is a type from one of the following: movie , tv or musical.
 [x]🔗 There is a link to the IMDB page or Playbill archive page under itemLink.
 [x]3️⃣ There are at least three emojis listed under emojiImgs.
 [x]5️⃣ There is a maximum of five emojis listed under emojiImgs.
 [x]👍 The pull request has a descriptive title (such as Added The Lion King or Added Black Panther, The Avengers: Endgame and Thor).
 [x]⭐ The genres are all inside of square brackets [ ] and each are individually wrapped in quotation marks and have a comma between each one. (such as submitting this "genres": ["adventure","mystery","animation"] and not this "genres":["adventure, mystery, animation"]).

### CODE REVIEW

**Comment by brittanyrw** [comment]
Hi @wdixon2186!

You are still missing a couple of steps from the card overview file. The object should be in alphabetical order so you need to move it down into the B section. And the ref parameter should not be included in the IMDB link. It should just be `https://www.imdb.com/title/tt1065073/`.

Also please delete the package-lock.json file. Thanks!

**Comment by wdixon2186** [comment]
Thank you. I'll fix those now.

**Comment by wdixon2186** [comment]
I just pushed with those changes.

**Comment by brittanyrw** [comment]
Awesome, your addition will be live on emojiscreen.com in a few minutes!

**Pull request merged**
