### PR TITLE
Added Matilda the musical(#282),The Princess Bride(#280),Mr.Robot(#277)

### PR DESCRIPTION
**Pull request by sumanismcse**
Added Matilda

### CODE REVIEW

**Comment by brittanyrw** [comment]
@sumanismcse Thanks for contributing to EmojiScreen! It looks like you deleted the to do list that was in the pull request. Please review the list here and make updates to your code: https://github.com/brittanyrw/emojiscreen/blob/master/pull_request_template.md

The last item on the to do list does not look complete yet. The shows should be placed in alphabetical order in the data.js file instead of all at the bottom. Once you have made that update I will review your code again. 

Thanks!

**Comment by brittanyrw** [comment]
Also it looks like the Princess Bride is already in the project. I am going to close that issue. Please remove the Princess Bride from your code.

Thanks!

**Comment by sumanismcse** [comment]
@brittanyrw  Thank you for reviewing the code. It was my mistake, I didn't read the last instruction.
I have already updated the code and arranged the movies in alphabetical order.

**Review by brittanyrw — APPROVED** [review]

**Comment by brittanyrw** [comment]
@sumanismcse thanks for contributing to EmojiScreen! 💜You should be able to see your addition at [emojiscreen.com](emojiscreen.com) soon.

**Pull request merged**
