### PR TITLE
Added Cats (musical)

### LINKED ISSUE #192: Add Cats (Musical)
Add Cats to EmojiScreen.

Link: http://www.playbill.com/production/cats-winter-garden-theatre-vault-0000011527

### PR DESCRIPTION
**Pull request by gmarwell**
Thanks for the lesson!

- [x] 🔍 I have searched the `data.js` file and confirmed I am not adding a duplicate entry. Note: Different versions of the same show/movie are okay to add such as Lion King (1994) and Lion King (2019) or Rent (movie) and Rent (musical).
- [x] 🌈 I have added a single year under `year`. Note: Do not add ranges such as 2017-2019.
- [x] 📅 I have added a type from one of the following: `movie` , `tv` or `musical`.
- [x] 🔗 I have added the IMDB page or Playbill archive page under `itemLink`.
- [x] 3️⃣ I have at least three emojis listed under `emojiImgs`.
- [x] 5️⃣ I have a maximum of five emojis listed under `emojiImgs`.
- [x] 👍 My pull request has a descriptive title (such as `Added The Lion King` or `Added Black Panther, The Avengers: Endgame and Thor`).
- [x] ⭐ My genres are all inside of square brackets `[ ]` and each are individually wrapped in quotation marks and have a comma between each one. (such as submitting this `"genres": ["adventure","mystery","animation"]` and not this `"genres":["adventure, mystery, animation"]`).
- [x] 🖍️ I have placed the new show(s) or movie(s) in alphabetical order based on title. If the show or movie starts with 'the', then use the second word to alphabetize.

Closes #192

### CODE REVIEW

**Comment by brittanyrw** [comment]
Hi @gmarwell, please update your emojis for Anchorman. There is a minimum of three emojis for the emoji cards. Thanks!

And just an informational note: We have paused contributions (new pull requests, issues and comments) on this project for today so we can review the backlog of pull requests. You should be able to update this PR, just not make new ones at the moment.

**Comment by gmarwell** [comment]
Just added the 3rd emoji to Anchorman; hopefully you can also merge in the addition of Cats to the musicals, unless there were also issues with that?

**Comment by brittanyrw** [comment]
@gmarwell Thanks! And there is no problem with Cats. It is just that your other Pull Request for Anchorman also had Cats included so I closed this one.

**Comment by gmarwell** [comment]
Ok, thank you again!
ᐧ

**Pull request closed without merging**
