### PR TITLE
Added expand all cards button

### LINKED ISSUE #37: Add an expand all cards button to the homepage.
Right now on the homepage, to see the name of the show or movie, the user has to click on the card. Create a button that will allow users to expand or collapse all cards at once.

### PR DESCRIPTION
**Pull request by renorram**
Added a fixed button on bottom to expand all cards.

Closes #37

### CODE REVIEW

**Comment by brittanyrw** [comment]
@renorram Ah this is amazing! 🤩I love the design that you came up with.

Did you also want to tackle the positioning of the button on mobile before I merge?

**Comment by renorram** [comment]
@brittanyrw thanks! 🤘 And yes I'll take a look on how it's on mobile before merge, great reminder.

**Comment by renorram** [comment]
@brittanyrw done! Please check if it's better now, I tried to find the better position it could be so it doesn't cover up much of the cards content. I tested using firefox.

**Comment by brittanyrw** [comment]
@renorram Thanks so much. This looks awesome!

**Pull request merged**
