### PR TITLE
Added Watchmen movie

### PR DESCRIPTION
**Pull request by RodolfoBrian**
**added  Watchmen movie**

### CODE REVIEW

**Comment by brittanyrw** [comment]
Hi @RodolfoBrian, it looks like you did not follow the instructions in the [card overview](https://github.com/brittanyrw/emojiscreen/blob/master/docs/card_overview.md) for adding a movie. Please update your pull request and follow the checklist in the link above. Otherwise I will be closing this, thanks!

**Review by RodolfoBrian — COMMENTED** [review]
All seem right,  i am don't see any issue here

**Review by RodolfoBrian — COMMENTED** [review]
Specify if the card you are adding is tv, "movie" or musical. 

> Only add one type per card.
modified  one type per card

**Comment by brittanyrw** [comment]
The object should be in alphabetical order based on title.

**Comment by RodolfoBrian** [comment]
> The object should be in alphabetical order based on title.

Thank you!! I was struggling to understand the issue.

**Comment by brittanyrw** [comment]
Thanks for updating. I will make the instructions more clear. :)

**Comment by brittanyrw** [comment]
You should be able to see your addition on emojiscreen.com in the next few minutes!

**Pull request merged**
